name: tiki_trail
description: Create and enforce TIKI's immutable data transaction records.
version: 3.0.3
homepage: https://mytiki.com
documentation: https://mytiki.com/docs
repository: https://github.com/tiki/tiki-trail
issue_tracker: https://github.com/tiki/tiki-trail/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pointycastle: ^3.7.3
  sqlite3: ^1.11.2
  http: ^1.0.0
  html: ^0.15.3
  uuid: ^3.0.7
  tiki_idp: ^0.1.0

dev_dependencies:
  test: ^1.24.3
  flutter_lints: ^2.0.1
  build_web_compilers: ^4.0.3
  nock: ^1.2.2
  build_runner: ">=1.6.2 <3.0.0"


