name: Version

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  version:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semver.outputs.nextStrict }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout PR
        id: getpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          export PR_BRANCH=$(git branch --show-current)
          echo "branch=$PR_BRANCH" >> $GITHUB_OUTPUT
          
      - name: Get Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: ${{ steps.getpr.outputs.branch }}

      - name: Set Version
        run: |
          sed -i 's/version:*.*.*/version: ${{ steps.semver.outputs.nextStrict }}/' pubspec.yaml

      - name: 'Setup Dart'
        uses: dart-lang/setup-dart@v1.4
        with:
          sdk: 3.0.3

      - name: Commit Changes
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GH Action"
          git add pubspec.yaml
          git commit -m 'version bump'
          git push